repository:
  name: chat2md
  default_branch: main
  has_issues: true
  has_projects: false
  has_wiki: false
  allow_merge_commit: true
  allow_squash_merge: true
  allow_rebase_merge: false

branches:
  - name: main
    protection:
      required_status_checks:
        strict: true
        contexts:
          - 'python.yml' # Replace with your actual workflow name if needed
      enforce_admins: false
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
      restrictions: null
      allow_force_pushes: false
      allow_deletions: false
