name: Python Lint & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .

    - name: Run linter
      run: |
        pip install flake8
        flake8 chat2md

    - name: Run sample conversion
      run: |
        chat2md tests/test_sample.json tests/output.md
